### ISSUE TITLE
how the visualisation works? & keras update

### ISSUE THREAD

**Issue by Xenonshi** [ackw/mbti-prediction-tool#1]
How does the visualisation part work? It seems that it has nothing to do with my input.

another issue is with the keras package.

keras has been updated, so if you run the original code it may cause attribute error:AttributeError: module 'keras.preprocessing.sequence' has no attribute 'pad_sequences'

check this out:

https://stackoverflow.com/questions/72326025/cannot-import-name-pad-sequences-from-keras-preprocessing-sequence

**Comment by ackw** [comment]
hi the visualisation is not dynamic, as its based on the EDA from the dataset. As for the keras packages, it is likely that an older version of keras was used during the preprocessing phase.
