### ISSUE TITLE
Possible corrupted model

### ISSUE THREAD

**Issue by harris-mohamed** [ackw/mbti-prediction-tool#2]
Hi, 

I was trying to run this code. The demo app runs great, but when running this locally I keep getting `OSError: Unable to open file (file signature not found)`. Did you ever run into this?

**Comment by ackw** [comment]
hi harris, I believe the issue stems from the model files (possibly damaged after uploading to github). Instead, you can consider replacing the files found [here](https://drive.google.com/drive/folders/11hstfX7Jo7WNiAURPjTKQ4fStmkC7Ekq?usp=sharing) :)
